# Site settings
title:       Dr. DRR
email:       'domsdagur@protonmail.com'
description: "In the darkest hour, there's always a way out."
baseurl:     '' # The subpath of your site, e.g. /blog
url:         'https://drdrr.xyz/'
twitter:     'https://twitter.com/'
github:      'https://github.com/'
instagram:   'https://instagram.com/'
facebook:    'https://facebook.com/'

markdown:  kramdown
permalink: pretty
paginate:  10

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext